CREATE DATABASE IF NOT EXISTS companydb;

CREATE TABLE employees(
id INT(11) NOT NULL AUTO_INCREMENT,
name VARCHAR(45) DEFAULT NULL,
salary INT(5) DEFAULT NULL,
PRIMARY KEY(id)
);

INSERT INTO employees VALUES 
(DEFAULT,"Joe", 1000),
(DEFAULT,"Henry", 2000),
(DEFAULT,"Sam", 2500),
(DEFAULT,"Max", 1500),
